### ISSUE TITLE
ed25519 does not work with node 12

### ISSUE THREAD

**Issue by vegarringdal** [erikma/passport-sqrl#10]
`ed25519` does not work with node 12.

https://github.com/gaoxiangxyz/ed25519/issues/1

**Comment by vegarringdal** [comment]
More info:

Window 10 Pro. 1909- OS build: 18386.657
Node v 12.14.0
Npm 6.13.4

**Comment by erikmav** [comment]
Added Node 12 PR to the upstream: https://github.com/gaoxiangxyz/ed25519/pull/2

**Comment by erikmav** [comment]
Published package version 0.3.0 with Node 12 updates
